### ISSUE TITLE
Move the project to an organization

### ISSUE THREAD

**Issue by dmitry-timofeev** [prevoty/jni-rs#104]
@jechase, @anandkunal , 

Thank you for putting together and open-sourcing Rust JNI project. We at Exonum have been [using](https://github.com/exonum/exonum-java-binding/) it for more than a year and are interested in its further development. 

Our team is grateful to you for reviewing and integrating our patches so far, however, it seems to us the project has ceased to be your top priority recently. For this reason, I suggest moving it under a new organization “JNI-rs” and giving more people permission to integrate changes and publish new versions of it on crates.io. In this way the project can evolve, enlarge its community, acquire better maintenance and improve in quality.

We understand it takes efforts maintaining an open-source project and would like to offer help with that. As you may know, members of Exonum team — @DarkEld3r , @alexander-irbis — have contributed various fixes and improvements to Rust JNI as well as reviewed every patch submitted to the project in the last year. Our team has expertise in running open-source projects in Rust, [Exonum](https://github.com/exonum/exonum) being the most prominent example.

Please consider further development of your project in a modified manner as suggested above and let us know your thoughts on the matter. You are free to contact our team members or me directly for discussion.

**CC** recent contributors: @paulrouget, @daschl, @mmastrac ,  @fpoli , @nbaksalyar , @king6cong , @mehcode

**Comment by nbaksalyar** [comment]
I fully support this proposal. We use `jni-rs` extensively at MaidSafe for our [Java bindings](https://github.com/maidsafe/safe_client_libs/tree/master/safe_app_jni) too.

Personally, I would be happy to help in the maintenance of this project.

**Comment by paulrouget** [comment]
I support this. We use it for Servo's Java bindings and would love to see more people involved in the development and maintenance of this crate.

**Comment by jechase** [comment]
Hey all, sorry for my long absence. You're absolutely right - this project hasn't been at the top of our priorities for some time and I haven't had time to give it the attention that it deserves. What's more, we were recently [acquired by Imperva](https://www.imperva.com/blog/2018/07/imperva-to-acquire-dev-ops-security-leader/), which throws my ability to contribute to open source projects into a state of limbo for the time being, at least as far as my day job is concerned.

Anyway, I'm all for the suggested reorg. I went ahead and created the organization as suggested and invited @dmitry-timofeev, @DarkEld3r, and @alexander-irbis. I'm going to hang onto the crates.io name for the next few days while I figure out what relationship the company wants to have with the project, but ideally, I'd like to pass those permissions along as well.

Thanks again for the ongoing contributions! I'll close this and see about getting issues/PRs migrated.

**Comment by dmitry-timofeev** [comment]
Hi Josh,

Awesome, thank you! All the best at Imperva!
