### ISSUE TITLE
UnsatisfiedLinkError with objects as parameter

### ISSUE THREAD

**Issue by CromefireHD** [prevoty/jni-rs#11]
I get an UnsatisfiedLinkError with this method:
```
FastCompute.arrayAddRS(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/String
```
Rust:
```rust
#[no_mangle]
#[allow(non_snake_case)]
#[allow(unused_variables)]
pub extern "C" fn Java_FastCompute_arrayAddRS(env: JNIEnv, class: JClass, a: JObject, b: JObject) -> jstring {
    [...]
}
```

Java:
```java
private native String arrayAddRS(Object a, Object b);
```

My other method (`FastCompute.addRS.(II)I`) is working without any problems

**Comment by Pursuit92** [comment]
I can't reproduce this - any more info you can give me?

**Comment by CromefireHD** [comment]
My Java classes:
[FastCompute.java.txt](https://github.com/prevoty/jni-rs/files/974358/FastCompute.java.txt)
[Main.java.txt](https://github.com/prevoty/jni-rs/files/974359/Main.java.txt)

My rust file:
[lib.rs.txt](https://github.com/prevoty/jni-rs/files/974369/lib.rs.txt)

Error occurrences when call the method:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: FastCompute.arrayAddRS(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;
	at FastCompute.arrayAddRS(Native Method)
	at FastCompute.arrayAdd(FastCompute.java:27)
	at Main.main(Main.java:13)
```

**Comment by Pursuit92** [comment]
So by the time I've taken out all of the things that make it not build for me (Compute / BaseClass inheritance, exceptions, and Library class), it all executes fine. 

Here's the whole thing:
[fastcompute.zip](https://github.com/prevoty/jni-rs/files/974433/fastcompute.zip)

**Comment by CromefireHD** [comment]
Seems to be working, looks to be an issue on my side
