### ISSUE TITLE
jvalue has no field _data anymore

### ISSUE THREAD

**Issue by ndusart** [prevoty/jni-rs#17]
The crate jni_sys has renamed the field `_data` of struct `jvalue` to `data`, hence this crate does not compile anymore due to this line in jvalue.rs (line 54):

```rust
trace!("converted {:?} to jvalue {:?}", self, val._data);
```

**Comment by ndusart** [comment]
This is [the commit](https://github.com/sfackler/rust-jni-sys/commit/f075705a9b092bfa5fccc01763ad89d352caeb8d) that renamed the field.

The field is no longer public either, I didn't see any function that expose the value. Maybe the solution is just to remove the log or the post an issue on rust-jni-sys repository for exposing the field again.

**Comment by DenisKolodin** [comment]
Will work again soon: https://github.com/sfackler/rust-jni-sys/pull/6

**Comment by jechas01** [comment]
Fixed in https://github.com/prevoty/jni-rs/commit/29a786d627e8f55038ce1aa75ee1a9024f934bf4

**Comment by ndusart** [comment]
Did not see there was a PR for this. I was looking for issues.
Great to know it is fixed :-)
