### ISSUE TITLE
Bytes signed/unsigned inconsistency

### ISSUE THREAD

**Issue by DarkEld3r** [prevoty/jni-rs#19]
Currently there are four functions that work with bytes: 
- `new_byte_array`: takes ` &[i8]`
- `convert_byte_array`: returns `Vec<u8>`
- `new_direct_byte_buffer`: takes `&mut [u8]`
- `get_direct_buffer_address`: returns `&mut [u8]`
Most of them work with unsigned bytes and that is consistent with Rust standard library, but `new_byte_array` expects slice of signed bytes, what is more Java-like. 

I prefer to change `new_byte_array` signature (and happy to submit a patch), but that will be a breaking change. Is it OK?

**Comment by jechas01** [comment]
Yeah, that's fine with me. I can just make it a minor version bump.
