### ISSUE TITLE
Calling methods on GlobalRef

### ISSUE THREAD

**Issue by angel-manuel** [prevoty/jni-rs#25]
It is possible to call methods on a GlobalRef?

JNIEnv::call_method takes an JObject and i don't see any way to convert between the types.

**Comment by DarkEld3r** [comment]
I had the same question: #24. I suppose it isn't possible now, so I'm going to try to fix it in the nearest future if you don't make it first. 😄

**Comment by jechas01** [comment]
Fixed in #26
