### ISSUE TITLE
`new_object_by_id` probably should take `JStaticMethodID` instead of `JMethodID`

### ISSUE THREAD

**Issue by DarkEld3r** [prevoty/jni-rs#33]
Constructor is a static method, so I made a mistake in the #29.

**Comment by dmitry-timofeev** [comment]
Java constructor is not a static method. You obtain a method id of a constructor with [`GetMethodID`](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#GetMethodID)

**Comment by DarkEld3r** [comment]
Then we have one less problem. :smile: I was confused by Rust "constructors" which are static methods.
