### ISSUE TITLE
Wrapper for local reference automatical deletion

### ISSUE THREAD

**Issue by DarkEld3r** [prevoty/jni-rs#34]
Sometimes it is important to manually delete the local references. I have made a simple wrapper for that:
```rust
pub struct AutoLocalRef<'a> {
    object: jobject,
    env: &'a JNIEnv<'a>,
}

impl<'a> AutoLocalRef<'a> {
    pub fn new(env: &'a JNIEnv<'a>, object: jobject) -> Self {
        Self { object, env }
    }

    pub fn as_obj(&self) -> JObject {
        self.object.into()
    }
}

impl<'a> Drop for AutoLocalRef<'a> {
    fn drop(&mut self) {
        if let Err(e) = self.env.delete_local_ref(self.object.into()) {
            error!("Unable to delete local reference: {}", e.description());
        }
    }
}
```
Typical use case: 
```rust
fn make_java_object<'a>(env: &JNIEnv<'a>, value: &Value) -> Result<JObject<'a>> {
    let value = AutoLocalRef::new(env, env.byte_array_from_slice(value)?);
    env.new_object(
        "com/project/foo/bar/baz/ClassName",
        "([B)V",
        &[value.as_obj().into()],
    )
}
```
This function is used for building tree-like structure, so local references must be deleted because there can be many nodes.

Questions:
1. Will it be useful to have such wrapper in the `jni-rs` library?
2. Wrapper stores `jobject` inside and has method for conversion it to the `JObject` because this allows to clone internal object: many functions take `JObject` by value and reference must be deleted after that. Perhaps this can be handled better somehow.

**Comment by jechas01** [comment]
I like the idea - maybe make it match the GlobalRef wrapper?

**Comment by jechas01** [comment]
OK, got an implementation of this in the develop branch. If you would, take a look and make sure I haven't missed anything obvious and that it works for your use case.

**Comment by DarkEld3r** [comment]
Nice, I see no problem in your code. I will try to replace our wrapper with `AutoLocal` and let you know the result.

**Comment by jechas01** [comment]
Okie doke, merged the wrapper into master and bumped the version to 0.6.0, so you should be able to get it from crates.io.
