### ISSUE TITLE
Segmentation fault thrown when trying to instantiate an object

### ISSUE THREAD

**Issue by Redrield** [prevoty/jni-rs#4]
When trying to instantiate an object of the calling class of a native method, the code fails to execute and crashes the JVM with a SIGSEGV

Crash log https://hastebin.com/finariguju.tex
Relevant code https://hastebin.com/xazukoguti.js

**Comment by Pursuit92** [comment]
No longer a problem? I literally just sat down to try to reproduce this :D

**Comment by Redrield** [comment]
I'm really sorry, I was passing a JClass to a non static method and was trying to call methods on it. This was 110% a PEBCAK error :P
