### ISSUE TITLE
Return Option<jobject>

### ISSUE THREAD

**Issue by dbrgn** [prevoty/jni-rs#42]
I have a function signature where I want to return an object instance or null.

I tried returning an `Option<jobject>`, but then the Rust code panics :)

Is there a way to return a null pointer?

**Comment by dbrgn** [comment]
Ah, this seems to work:

    ptr::null_mut() as *mut _jobject

Maybe that could somehow be made more ergonomic? Via an `Option` would be fantastic, but even a provided helper function creating such a null-jobject would be nice.

**Comment by jechas01** [comment]
Do you mean that you're trying to return either a `jobject` or a null pointer from an `extern "C"` function? I think that the "`Option` to represent a null ffi pointer" pattern is mainly used for function pointers. I'm pretty sure that returning an `Option` to C-land doesn't work in the same manner, so it won't be possible to do that here. A helper should be pretty easy though.

**Comment by dbrgn** [comment]
> Do you mean that you're trying to return either a jobject or a null pointer from an extern "C" function?

Exactly. In Java it would be something like this:

```java
public MyObject foo() {
    if (...) {
        return new MyObject();
    } else {
        return null;
    }
}
```

**Comment by jechas01** [comment]
Going ahead and closing this since I'm like 95% sure that returning an option from an FFI function is not and likely will never be possible, and the helper for constructing a null object made its way into 0.6.1.

If you can find anything to the contrary on the option return, feel free to reopen!

**Comment by dbrgn** [comment]
Would something like that work? https://github.com/llogiq/optional/issues/23
