### ISSUE TITLE
How to use primitives like 'jint', 'jbyte', etc. ?

### ISSUE THREAD

**Issue by ice1000** [prevoty/jni-rs#5]
I'm a beginner to Rust and I have no idea how to write the equivalent Rust code of the C++ code below:
```cpp
JNIEXPORT auto JNICALL Java_foo_Bar_foo(
		JNIEnv *env,
		jclass,
		jint num,
		jintArray _data) -> jintArray {
	jboolean *option = nullptr;
	auto len = env->GetArrayLength(_data);
	auto data = env->GetIntArrayElements(_data, option);
	env->ReleaseIntArrayElements(_data, data, JNI_ABORT);
	auto _ret = env->NewIntArray(len);
	env->SetIntArrayRegion(_ret, 0, len, ret);
	return _ret;
}
```

Sorry for my English.

**Comment by ice1000** [comment]
I've read the doc and examples, without getting any answer. 😭

**Comment by ice1000** [comment]
I've tried:

```rust
pub extern fn Java_foo_Bar_foo(env: JNIEnv, jc: JClass, i: jint) {
 // balabala
}
```

but failed

**Comment by Pursuit92** [comment]
You're going to have to be a bit more specific than "it failed." You've got the argument list specified correctly. Are you missing the `#[no_mangle]` attribute?

**Comment by Pursuit92** [comment]
Oh, and we don't currently support the primitive array operations you're using in the C++ example. Open to pull requests if you want to add the necessary methods though!

**Comment by ice1000** [comment]
well, I've already added `#[no_mangle]` . Actually what I need was how to use primitives...

**Comment by ice1000** [comment]
And I've got solution. I forgot 2 use:
```rust
use jni::sys::*;
```
My fault... 😂
