### ISSUE TITLE
How to use pop_local_frame(JObject::null())

### ISSUE THREAD

**Issue by fpoli** [prevoty/jni-rs#55]
I would like to call `env.pop_local_frame(JObject::null())`.

The documentation says that "resulting `JObject` can be `NULL` if `result` is `NULL`".
However, in my case `pop_local_frame` returns an `Err(NullPtr("PopLocalFrame result"))`.

Shouldn't the result be `Ok(something)`, since it's an expected behaviour?

**Comment by jechas01** [comment]
Yeah, that's probably a bug. Probably just using the wrong macro in the method body.
