### ISSUE TITLE
Warn a user when a GlobalRef is dropped with no thread attached

### ISSUE THREAD

**Issue by dmitry-timofeev** [prevoty/jni-rs#69]
Currently `DetachedGlobalRef` attaches a native thread to the JVM in its `#drop` function in case when the current native thread is not attached, and immediately detaches. That prevents a memory leak, but it also makes it easy to rely on this mechanism _frequently enough_ to introduce a performance bug and make your program come to a crawl. What makes it considerable, is that _frequently enough_ means thousands.

@alexander-irbis did a simple benchmark that constantly attaches a native thread, calls a simple Java method, and immediately detaches it. It shows tens of thousands ops per second. Such a slow throughput occurs because JVM creates a new thread when a detached native thread calls `AttachCurrentThread`. The results above align well with the results I obtained with a Java benchmark which simply creates threads that do nothing and stop: JVM creates ~40K threads per second on my laptop.

I'd suggest to log a warning message in the case described above, saying that if you see it once, it's OK, if you see it frequently -- consider reading the docs and fixing your app, because:
* This complex, slow behavior is hidden from a user, who is unlikely to know the underlying mechanics.
* Its results are less obvious than an OutOfMemoryError (in case of leaks).
* One needs to use a profiler to reveal the source of the problem.

This issue relates to `DetachedGlobalRef` as of v0.8.1, and a prospective new `GlobalRef` in #67, therefore, it's orthogonal to #66 .

**Comment by dmitry-timofeev** [comment]
+ recommend in the docs to prefer dropping the global ref when the native thread is already attached.

**Comment by DarkEld3r** [comment]
ooks like a good idea to me.
