### ISSUE TITLE
Documentation Link Down

### ISSUE THREAD

**Issue by EternalDeiwos** [prevoty/jni-rs#72]
The title says it all.

**Comment by fpoli** [comment]
Here is the log of the failed build: https://docs.rs/crate/jni/0.9.0/builds/81968
```
the `?` operator cannot be applied to type `std::option::Option<...>`
```

**Comment by alexander-irbis** [comment]
There is no problem with the current stable 1.23, but docs.rs still used 1.22.

**Comment by alexander-irbis** [comment]
https://github.com/onur/docs.rs/issues/171
