### ISSUE TITLE
How to throw exceptions from rust

### ISSUE THREAD

**Issue by onelson** [prevoty/jni-rs#76]
I'm working on a rust crate with some functions that return `Result` - I'm hoping use the `Err` values to generate exceptions for the Java caller, but I'm not confident I'm using the provided API in the intended way.

The reason I'm doubtful is I expected to be able to do something like this:

```rust

#[no_mangle]                                                                   
#[allow(non_snake_case)]                                                       
pub extern "system" fn Java_MyLib_getMaybeBool(                               
    env: JNIEnv,                                                               
    class: JClass,                                                             
    input: JString,                                                            
) -> jboolean {                                                                
    let input: String = env.get_string(input)                                  
        .expect("Couldn't get java string!")                                   
        .into();                                                               

    match get_maybe_bool(&input) {
        Ok(output) => output as u8, 
        Err(err) => {                                                          
            env.throw(err.to_string()).unwrap();
            unreachable!();
        }                                                                      
    }                                                                          
} 
```

When I write this, the java caller segfaults in the Err case, hitting the `unreachable!();` and then panics.

Instead, I'm returning a `0u8` following the throw, which I guess could be correct from a certain point of view (but not really). With the `0u8` return value, I see the caller get the exception and everything works how I'd think it should.

Am I missing some aspect of this? An example of throwing exceptions would be nice to have.

**Comment by jechase** [comment]
You still have to return to the JVM, even if you've thrown an exception.
Remember that unwinding across the ffi boundary is always undefined
behavior, so any panics need to be caught and recovered from in your extern
functions.

I can give more of an example tomorrow when I'm not replying from my phone

**Comment by onelson** [comment]
OK, that makes some good sense.

I suppose I could aim to document this with a `const BOOL_NOPE: u8 = 255;` and just return `BOOL_NOPE` in these situations.

I was just wondering if there was some way to model the throwing of the exception in the function signature (like you might with a `Result`).

**Comment by dmitry-timofeev** [comment]
That's a good question because this thing is tricky to handle properly. We ended up with the following (@DarkEld3r, please correct me if I'm wrong):
* If a native function panics -- throw a Java runtime exception.
* If a native function returns `Err`:
  * [check](https://docs.rs/jni/0.9.3/jni/struct.JNIEnv.html#method.exception_check) if there is a pending (= already thrown) Java exception, do nothing if that's the case.
  * otherwise -- throw a proper Java exception to let the caller know about the error.
* If a native function returns `Ok`: return to the Java side.

I can't say if this library can help with handling panics and errors, or simplify it.

**Comment by jechase** [comment]
There's nothing in this lib as of right now that can help with that, but it could be possible with the help of some macro magic.

Some time ago, I played around with wrapping the [wren](https://wren.io) in Rust and came up with a [macro system](https://github.com/jechase/thrush/blob/master/src/macros.rs) for doing some extra automatic translation of wren types -> rust types and adding safety wrappers. Example [here](https://github.com/jechase/thrush/blob/master/tests/foreigns.rs).

Something similar could conceivably be included here if someone had the motivation to build it 😉

**Comment by jechase** [comment]
I think the question here has effectively been answered, and I filed an enhancement issue for some of the ergonomics improvements proposed here, so I'm closing this one.

Feel free to discuss more ergonomics improvements in #80!
