### ISSUE TITLE
Example doesn't compile since GlobalRefGuard introduced.

### ISSUE THREAD

**Issue by harrybraviner** [prevoty/jni-rs#89]
Attempting to compile the code in `example/mylib` in the master branch leads to the following error:
```
error[E0599]: no method named `detach` found for type `jni::objects::GlobalRef` in the current scope
   --> src/lib.rs:137:29
    |
137 |     let callback = callback.detach().unwrap();
    |                             ^^^^^^

```

It looks like this is due to the change made in `a98e71f Reimplemented `GlobalRef` (#66)` when `GlobalRef` was made `Send`. Unfortunately I don't know enough about this to know how to fix it.

**Comment by harrybraviner** [comment]
I've just realised that there is a pull request open that fixes this: https://github.com/prevoty/jni-rs/pull/85/files/ed75b3d8c03e90acc289505514e22b73a3a85d6f

**Comment by jechase** [comment]
#85 is merged, so this should be good now!
