### ISSUE TITLE
strange memory usage and looks like a leak

### ISSUE THREAD

**Issue by king6cong** [prevoty/jni-rs#93]
I changed the example and run hello world in a loop, and memory usage keeps going up until around 165M and stops growing.

## changes:

https://github.com/king6cong/jni-rs/commit/4bedfbb5abc4ec5f89e92ff59a22ed4267fd4a61#diff-cc38745d93dc48d0cd2612e5d596dad5L15

## steps to reproduce:
```shell
git clone -b leak https://github.com/king6cong/jni-rs
cd jni-rs
cd example/mylib && cargo build && cd -
cd example && javac HelloWorld.java && java -Djava.library.path=mylib/target/debug/ HelloWorld
```

<img width="916" alt="image" src="https://user-images.githubusercontent.com/302560/39116227-777551c0-4716-11e8-80f4-78540377dce4.png">

This is strange, and not sure if this is a memory leak

**Comment by dmitry-timofeev** [comment]
Looked at the implementation of [the native method](https://github.com/king6cong/jni-rs/blob/4bedfbb5abc4ec5f89e92ff59a22ed4267fd4a61/example/mylib/src/lib.rs#L26) you called, and I didn’t see any obvious leaks. According to the specification, any local references registered in a native method will be released once the native method returns.

Probably, a tool is needed to understand what kind of objects are in the heap of this application, e.g., 
 [Eclipse Memory Analyzer](https://www.eclipse.org/mat/). 

Have you attempted to put in this loop periodic garbage collection requests (not at every iteration, but every _N_ iterations)?

**Comment by king6cong** [comment]
`jvisualvm` seems to have given a good explanation:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/302560/39178649-dad9383e-47e4-11e8-83fa-d3539cd99f9e.png">
<img width="732" alt="image" src="https://user-images.githubusercontent.com/302560/39178668-e641885c-47e4-11e8-8e56-dafd45997021.png">

so a good lot of live objects seem to be kept by jvm although they can be recycled earlier.
