### ISSUE TITLE
Call a Java method from Rust code

### ISSUE THREAD

**Issue by fasihrana** [prevoty/jni-rs#95]
Is there a fully contained example to call a Java method from Rust code?

Some thing like an example found on https://github.com/rustyhorde/rsjni

**Comment by dmitry-timofeev** [comment]
There is an integration test that calls various types of Java methods: https://github.com/prevoty/jni-rs/blob/master/tests/java_integers.rs

It shows how to start a JVM from Rust, how to attach the current native thread, and call a Java method. If Java calls Rust, the native thread is already attached and you can just do the latter.

**Comment by fasihrana** [comment]
I've written a sample to do this.  [fasihrana/rustjni_example](https://github.com/fasihrana/rustjni_example).

Hopefully this will help someone looking for a clear cut way.

My suggestion would be to add the `pub fn jvm() -> &'static Arc<JavaVM>` found in the [util/mod.rs](https://github.com/prevoty/jni-rs/blob/master/tests/util/mod.rs) file, to the actual API, taking in the arguments to start the jvm.

**Comment by fasihrana** [comment]
Closing this issue since I have a working example.
